In [2]:
import numpy as np

In [3]:
lst=[1,2,3,4,5]
arr=np.array(lst)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape #One dimensional Array

(5,)

In [9]:
arr1=np.array([[1,2,3],[4,5,6]])

In [10]:
arr1.shape #arr1 is a Two dimensional array

(2, 3)

In [11]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
ar=np.array((1,2,3,4,5))

In [15]:
ar

array([1, 2, 3, 4, 5])

In [16]:
arr1.dtype

dtype('int32')

In [21]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [22]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [25]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [33]:
np.linspace(1,20,40).reshape(20,2) #Equally spaced elements

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [34]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [39]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
np.ones((5,2,8)) #2,8 represents inner array 2 rows 8 columns(3D Array)

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [42]:
5+np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [44]:
np.eye(4).reshape(2,8)

array([[1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.]])

In [45]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [48]:
np.random.rand(2,3) #generating random nos from uniform distribution (always gives values between 0 to 1)

array([[0.71482991, 0.4155143 , 0.5321672 ],
       [0.82445338, 0.1698244 , 0.2180713 ]])

In [49]:
print("Random nos following a normal distribution mean=0, SD=1")
print(np.random.randn(3,4))

Random nos following a normal distribution mean=0, SD=1
[[-1.04302638  0.43846206  0.29206341 -0.44231399]
 [ 0.53315999  1.18937645  0.75287235 -2.12740039]
 [ 0.53610653 -0.21493575  0.52483638  0.62488985]]


In [50]:
np.random.randint(1,100)

14

In [56]:
np.random.randint(1,100,(4,4))

array([[83, 95, 68, 26],
       [30, 99, 17, 43],
       [24, 12, 53, 83],
       [52, 23,  6, 74]])

In [57]:
arr3=np.arange(0,11)

In [59]:
arr3[2:] #Slicing 

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr3[2:7]

array([2, 3, 4, 5, 6])

In [62]:
arr3[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [63]:
arr3[-1]

10

In [64]:
arr3[-1:7:-1]

array([10,  9,  8])

In [66]:
arr3[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])

In [67]:
arr3[-1:3:-2]

array([10,  8,  6,  4])

In [70]:
arr4=np.random.randint(2,100,20).reshape(5,4)
arr4

array([[84, 61, 84,  4],
       [90, 55, 46, 21],
       [49, 98, 72, 22],
       [15, 35, 61, 40],
       [97, 41, 92,  2]])

In [77]:
arr4[0:3,0:3]

array([[84, 61, 84],
       [90, 55, 46],
       [49, 98, 72]])

In [81]:
arr4[3:,1:]

array([[35, 61, 40],
       [41, 92,  2]])

In [83]:
arr4[2:4,1:3]

array([[98, 72],
       [35, 61]])

In [84]:
arr4[-3:-1,-3:-1]

array([[98, 72],
       [35, 61]])

In [85]:
arr4[2:4,1:4:2]

array([[98, 22],
       [35, 40]])

In [86]:
#Universal functions
